/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import edd_safeway.GrafoController;
import edd_safeway.InvoiceController;
import edd_safeway.PlaceController;
import edd_safeway.SecurityController;
import edd_safeway.TravelController;
import edd_safeway.UserController;
import edd_safeway.Usuario;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JOSED
 */
public class AdminInterface extends javax.swing.JFrame {
    
    private Usuario user;
    private UserController userController;
    private PlaceController placeController;
    private GrafoController grafoController;
    private InvoiceController invoiceController;
    private TravelController travelController;
    
    private FileNameExtensionFilter jsonFilter;

    /**
     * Creates new form AdminInterface
     */
    public AdminInterface() {
        initComponents();
        jsonFilter = new FileNameExtensionFilter("JSON","json");
        
        this.userController = UserController.getInstance();
        this.placeController = PlaceController.getInstance();
        this.grafoController = GrafoController.getInstance();
        this.invoiceController = InvoiceController.getInstance();
        this.travelController = TravelController.getInstance();
        this.user = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_user = new javax.swing.JLabel();
        btn_salir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        time_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_nuevaRuta = new javax.swing.JButton();
        btn_colocarTiempo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_reporte_usuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_reporte_conductores = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_reporte_facturas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_reporte_viajes = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_reporte_tablahash = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_json_usuarios = new javax.swing.JButton();
        label_ver_usuarios = new javax.swing.JLabel();
        label_ver_localidades = new javax.swing.JLabel();
        btn_json_localidades = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        label_ver_lugares = new javax.swing.JLabel();
        btn_json_lugares = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        label_ver_conexiones = new javax.swing.JLabel();
        btn_json_conexiones = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        label_ver_ubicaciones = new javax.swing.JLabel();
        btn_json_ubicaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(756, 422));

        label_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_user.setText("Administrador: Marvin");

        btn_salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(51, 51, 51));
        btn_salir.setText("Salir");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración"));

        jLabel1.setText("Tiempo de commit:");

        time_field.setText("3");

        jLabel2.setText("minutos");

        jLabel19.setText("Carpeta: C:\\SafeWay_EDD");

        btn_nuevaRuta.setText("Nueva ruta");
        btn_nuevaRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaRutaActionPerformed(evt);
            }
        });

        btn_colocarTiempo.setText("Colocar tiempo");
        btn_colocarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colocarTiempoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(time_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_colocarTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_nuevaRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(time_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevaRuta)
                    .addComponent(btn_colocarTiempo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Reportes"));

        btn_reporte_usuarios.setText("Ver reporte");
        btn_reporte_usuarios.setActionCommand("");
        btn_reporte_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_usuariosActionPerformed(evt);
            }
        });

        jLabel3.setText("- Reporte de Usuarios (árbol B)");

        jLabel4.setText("- Reporte de Conductores (árbol B)");

        btn_reporte_conductores.setText("Ver reporte");
        btn_reporte_conductores.setActionCommand("");
        btn_reporte_conductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_conductoresActionPerformed(evt);
            }
        });

        jLabel5.setText("- Reporte de Facturas (árbol B)");

        btn_reporte_facturas.setText("Ver reporte");
        btn_reporte_facturas.setActionCommand("");
        btn_reporte_facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_facturasActionPerformed(evt);
            }
        });

        jLabel6.setText("- Reporte de Viajes (árbol B)");

        btn_reporte_viajes.setText("Ver reporte");
        btn_reporte_viajes.setActionCommand("");
        btn_reporte_viajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_viajesActionPerformed(evt);
            }
        });

        jLabel7.setText("- Reporte de TablaHash");

        btn_reporte_tablahash.setText("Ver reporte");
        btn_reporte_tablahash.setActionCommand("");
        btn_reporte_tablahash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporte_tablahashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reporte_tablahash)
                            .addComponent(btn_reporte_conductores)
                            .addComponent(btn_reporte_usuarios)
                            .addComponent(btn_reporte_facturas)
                            .addComponent(btn_reporte_viajes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reporte_usuarios)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reporte_conductores)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reporte_facturas)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reporte_viajes)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reporte_tablahash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar archivos"));

        jLabel8.setText("Los archivos permitidos son en formato JSON");

        jLabel9.setText("1 - Archivo de Usuarios");

        btn_json_usuarios.setText("Cargar JSON");
        btn_json_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_json_usuariosActionPerformed(evt);
            }
        });

        label_ver_usuarios.setText("Ver ejemplo de archivo");
        label_ver_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ver_usuariosMouseClicked(evt);
            }
        });

        label_ver_localidades.setText("Ver ejemplo de archivo");
        label_ver_localidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ver_localidadesMouseClicked(evt);
            }
        });

        btn_json_localidades.setText("Cargar JSON");
        btn_json_localidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_json_localidadesActionPerformed(evt);
            }
        });

        jLabel12.setText("2.2 - Archivo de Localidades");

        label_ver_lugares.setText("Ver ejemplo de archivo");
        label_ver_lugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ver_lugaresMouseClicked(evt);
            }
        });

        btn_json_lugares.setText("Cargar JSON");
        btn_json_lugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_json_lugaresActionPerformed(evt);
            }
        });

        jLabel14.setText("2 - Archivo de Lugares");

        label_ver_conexiones.setText("Ver ejemplo de archivo");
        label_ver_conexiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ver_conexionesMouseClicked(evt);
            }
        });

        btn_json_conexiones.setText("Cargar JSON");
        btn_json_conexiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_json_conexionesActionPerformed(evt);
            }
        });

        jLabel16.setText("3 - Archivo de Conexiones");

        jLabel18.setText("2.1 - Archivo de ubicación de usuarios");

        label_ver_ubicaciones.setText("Ver ejemplo de archivo");
        label_ver_ubicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ver_ubicacionesMouseClicked(evt);
            }
        });

        btn_json_ubicaciones.setText("Cargar JSON");
        btn_json_ubicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_json_ubicacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_json_usuarios)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(label_ver_usuarios)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btn_json_ubicaciones)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(label_ver_ubicaciones))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btn_json_lugares)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(label_ver_lugares)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btn_json_localidades)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(label_ver_localidades)))))
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_json_conexiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_ver_conexiones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_json_usuarios)
                            .addComponent(label_ver_usuarios)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_json_ubicaciones)
                            .addComponent(label_ver_ubicaciones))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_json_localidades)
                            .addComponent(label_ver_localidades)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_json_lugares)
                            .addComponent(label_ver_lugares))))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_json_conexiones)
                    .addComponent(label_ver_conexiones))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_user)
                    .addComponent(btn_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        
        //Regresar a LogIn
        LogIn login = new LogIn();
        login.setVisible(true);
        System.out.println(" | > Log Out");
        
        this.dispose();
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_reporte_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_usuariosActionPerformed
        
        //Mostrar reporte de Usuarios árbol B
        if(!userController.viewUserTree()){
            JOptionPane.showMessageDialog(this, "No hay usuarios registrados", "B tree Users", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Abrindo PDF", "B tree Users", JOptionPane.PLAIN_MESSAGE);
        }
                
                
    }//GEN-LAST:event_btn_reporte_usuariosActionPerformed

    private void btn_reporte_conductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_conductoresActionPerformed
        
        //Mostrar reporte de conductores árbol B
        if(!userController.viewDriverTree()){
           JOptionPane.showMessageDialog(this, "No hay usuarios registrados", "B tree Drivers", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Abrindo PDF", "B tree Drivers", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_reporte_conductoresActionPerformed

    private void btn_reporte_facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_facturasActionPerformed
        
        //Mostrar reporte de facturas árbol B
        if(!invoiceController.viewInvoicesTree()){
           JOptionPane.showMessageDialog(this, "No hay facturas registrados", "B tree Invoices", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Abrindo PDF", "B tree Invoices", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_reporte_facturasActionPerformed

    private void btn_reporte_viajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_viajesActionPerformed
        
        //Mostrar reporte de facturas árbol B
        if(!travelController.viewTravelsTree()){
           JOptionPane.showMessageDialog(this, "No hay viajes registrados", "B tree Travel", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Abrindo PDF", "B tree Travel", JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_reporte_viajesActionPerformed

    private void btn_reporte_tablahashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporte_tablahashActionPerformed
        
        //Mostrar reporte de lugares tabla hash
        if(!placeController.viewPlacesHashTable()){
          JOptionPane.showMessageDialog(this, "No hay lugares registrados", "Hash Table", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Abrindo PDF", "Hash Table", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btn_reporte_tablahashActionPerformed

    private void btn_json_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_json_usuariosActionPerformed
        
        //Cargar archivo JSON de Usuarios
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Cargar usuarios - JSON");
        fileChooser.setFileFilter(jsonFilter);
        int selection = fileChooser.showOpenDialog(this);
        
        if(selection == JFileChooser.APPROVE_OPTION){
            int request = userController.loadUsers(fileChooser.getSelectedFile());
            if( request >= 0){
                JOptionPane.showMessageDialog(this, request + " usuarios cargados con éxito", "JSON Usuarios", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el JSON", "JSON Usuarios", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_json_usuariosActionPerformed

    private void btn_json_lugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_json_lugaresActionPerformed
        
        //Cargar archivo JSON de Lugares
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Cargar lugares - JSON");
        fileChooser.setFileFilter(jsonFilter);
        int selection = fileChooser.showOpenDialog(this);
        
        if(selection == JFileChooser.APPROVE_OPTION){
            
            int request = placeController.loadPlaces(fileChooser.getSelectedFile());
            if( request >= 0){
                JOptionPane.showMessageDialog(this, request + " lugares cargados con éxito", "JSON Lugares", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el JSON", "JSON Lugares", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_json_lugaresActionPerformed

    private void btn_json_conexionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_json_conexionesActionPerformed
        
        //Cargar conexiones en grafo
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Cargar rutas (Grafo) - JSON");
        fileChooser.setFileFilter(jsonFilter);
        int selection = fileChooser.showOpenDialog(this);
        
        if(selection == JFileChooser.APPROVE_OPTION){
            int request = grafoController.loadConections(fileChooser.getSelectedFile());
            if( request >= 0){
                JOptionPane.showMessageDialog(this, request + " las conexiones cargadas con éxito", "JSON Grafo", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el JSON", "JSON Grafo", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btn_json_conexionesActionPerformed

    private void btn_json_ubicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_json_ubicacionesActionPerformed
        
        //Cargar archivo JSON de ubicaciones de usuario
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Ubicación de usuarios - JSON");
        fileChooser.setFileFilter(jsonFilter);
        int selection = fileChooser.showOpenDialog(this);
        
        if(selection == JFileChooser.APPROVE_OPTION){
            
            int request = placeController.loadUsersLocation(fileChooser.getSelectedFile());
            if( request >= 0){
                JOptionPane.showMessageDialog(this, request + " usuarios actualizados con éxito", "JSON Localidades", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar ningun usuario al cargar el JSON", "JSON Localidades", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_json_ubicacionesActionPerformed

    private void btn_json_localidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_json_localidadesActionPerformed
        
        //Cargar archivo JSON de ubicaciones de usuario
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Ubicación de conductores - JSON");
        fileChooser.setFileFilter(jsonFilter);
        int selection = fileChooser.showOpenDialog(this);
        
        if(selection == JFileChooser.APPROVE_OPTION){
            
            int request = placeController.loadDriversLocation(fileChooser.getSelectedFile());
            if( request >= 0){
                JOptionPane.showMessageDialog(this, request + " conductores actualizados con éxito", "JSON Localidades", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar ningun conductor al cargar el JSON", "JSON Localidades", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btn_json_localidadesActionPerformed

    private void btn_colocarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colocarTiempoActionPerformed
        
        //Btn colocar tiempo
        try {
            int t = Integer.parseInt(this.time_field.getText());
            
            SecurityController.getInstance().setTime(t);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_colocarTiempoActionPerformed

    private void btn_nuevaRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaRutaActionPerformed
        
        //Obtener Ruta para la nueva carpeta
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar carpeta para guardar los datos del programa");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if(chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            
            System.out.println(" | > Directorio raiz cambiado a: " + chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btn_nuevaRutaActionPerformed

    private void label_ver_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ver_usuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ver_usuariosMouseClicked

    private void label_ver_lugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ver_lugaresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ver_lugaresMouseClicked

    private void label_ver_conexionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ver_conexionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ver_conexionesMouseClicked

    private void label_ver_ubicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ver_ubicacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ver_ubicacionesMouseClicked

    private void label_ver_localidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ver_localidadesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ver_localidadesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_colocarTiempo;
    private javax.swing.JButton btn_json_conexiones;
    private javax.swing.JButton btn_json_localidades;
    private javax.swing.JButton btn_json_lugares;
    private javax.swing.JButton btn_json_ubicaciones;
    private javax.swing.JButton btn_json_usuarios;
    private javax.swing.JButton btn_nuevaRuta;
    private javax.swing.JButton btn_reporte_conductores;
    private javax.swing.JButton btn_reporte_facturas;
    private javax.swing.JButton btn_reporte_tablahash;
    private javax.swing.JButton btn_reporte_usuarios;
    private javax.swing.JButton btn_reporte_viajes;
    private javax.swing.JLabel btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_user;
    private javax.swing.JLabel label_ver_conexiones;
    private javax.swing.JLabel label_ver_localidades;
    private javax.swing.JLabel label_ver_lugares;
    private javax.swing.JLabel label_ver_ubicaciones;
    private javax.swing.JLabel label_ver_usuarios;
    private javax.swing.JTextField time_field;
    // End of variables declaration//GEN-END:variables

    public void setUser(Usuario user){
        this.user = user;
        
        this.label_user.setText(user.getNombre() + " (@"+ user.getUsuario()+")");
    }
}
